name: CodeCheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
        pip install flake8
        pip install pylint
        pip install mypy
        pip install -r mypy_stubs.txt

    - name: Lint with flake8
      id: lint-flake8
      run: |
        flake8 . --count --show-source --statistics --max-line-length 82 || echo "::set-env name=ERRORS::true"

    - name: Lint with pylint
      id: lint-pylint
      run: |
        pylint $(git ls-files '*.py') || echo "::set-env name=ERRORS::true"

    - name: Lint with mypy
      id: lint-mypy
      run: |
        mypy $(git ls-files '*.py') || echo "::set-env name=ERRORS::true"

    - name: Run tests
      id: run-tests
      run: |
        pytest || echo "::set-env name=ERRORS::true"

    - name: Check for errors
      run: |
        if [ "${{ env.ERRORS }}" == "true" ]; then
          echo "Errors were found in linting or tests."
          exit 1
        fi
