name: CodeCheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
        pip install flake8
        pip install pylint
        pip install mypy
        pip install -r mypy_stubs.txt

    - name: Lint with flake8
      continue-on-error: true
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --show-source --statistics --max-line-length 82

    - name: Lint with pylint
      continue-on-error: true
      run: |
        pylint $(git ls-files '*.py')

    - name: Lint with mypy
      continue-on-error: true
      run: |
        mypy $(git ls-files '*.py')

    - name: Run tests
      continue-on-error: true
      run: |
        pytest